# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: doancnpm
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: quan-ly-dai-ly
# "service" is the name of this project. This will also be added to your AWS resource names.
service: loai-dai-ly

provider:
  name: aws
  runtime: nodejs22.x
  timeout: 45
  environment:
    DATABASE_REGION: ${env:DB_REGION}
    DATABASE_USER: ${env:DB_USER} # Configure your database credentials as environment variables
    DATABASE_HOST: ${env:DB_HOST}
    DATABASE_NAME: ${env:DB_NAME}
    DATABASE_PORT: ${env:DB_PORT}
  httpApi:
    cors: true
    # Optional: increase timeout if needed
    timeout: 30

custom: 
  webpack:
    webpackIncludeModules: true

functions:
  createldl:
    handler: handler.createldl
    events:
      - httpApi:
          path: /loai-dai-ly
          method: post
  
  getallldl:
    handler: handler.getallldl
    events:
      - httpApi:
          path: /loai-dai-ly
          method: get
  
  getldlbyid:
    handler: handler.getldlbyid
    events:
      - httpApi:
          path: /loai-dai-ly/{maLoaiDaiLy}
          method: get
  
  updateldl:
    handler: handler.updateldl
    events:
      - httpApi:
          path: /loai-dai-ly/{maLoaiDaiLy}
          method: put
  
  deleteldl:
    handler: handler.deleteldl
    events:
      - httpApi:
          path: /loai-dai-ly/{maLoaiDaiLy}
          method: delete