# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: doancnpm
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: quan-ly-dai-ly
# "service" is the name of this project. This will also be added to your AWS resource names.
service: don-vi-tinh

provider:
  name: aws
  runtime: nodejs22.x
  region: ${env:AWS_REGION}
  stage: ${opt:stage, 'dev'}
  memorySize: 128
  timeout: 10
  environment:
    DATABASE_REGION: ${env:DB_REGION}
    DATABASE_USER: ${env:DB_USER} # Configure your database credentials as environment variables
    DATABASE_HOST: ${env:DB_HOST}
    DATABASE_NAME: ${env:DB_NAME}
    DATABASE_PORT: ${env:DB_PORT}
  httpApi:
    disableDefaultEndpoint: true
    cors: true
  iam:
    role:
      statements:
        # Add basic Lambda permissions
        - Effect: Allow
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
          Resource: 'arn:aws:logs:*:*:*'
      # Add the Aurora DSQL managed policy
      managedPolicies:
        - 'arn:aws:iam::aws:policy/AmazonAuroraDSQLFullAccess'

plugins:
  - serverless-dotenv-plugin
  - serverless-offline

custom:
  dotenv:
    path: ../../.env
  serverless-offline:
    httpPort: 4003

layers:
  Dependencies:
    path: ../../lambda-aurora-dsql # required, path to layer contents on disk
    name: ${sls:stage}-pg-dsql-uuid # optional, Deployed Lambda layer name
    description: Package for postgres, dsql-signer and uuid # optional, Description to publish to AWS
    compatibleRuntimes: # optional, a list of runtimes this layer is compatible with
      - nodejs22.x
    compatibleArchitectures: # optional, a list of architectures this layer is compatible with
      - x86_64
    retain: false

functions:
  createdvt:
    handler: handler.createdvt
    layers:
      - !Ref DependenciesLambdaLayer
    events:
      - httpApi:
          path: /
          method: post
  
  getalldvt:
    handler: handler.getalldvt
    layers:
      - !Ref DependenciesLambdaLayer
    events:
      - httpApi:
          path: /
          method: get
  
  getdvtbyid:
    handler: handler.getdvtbyid
    layers:
      - !Ref DependenciesLambdaLayer
    events:
      - httpApi:
          path: /{maDonViTinh}
          method: get
  
  updatedvt:
    handler: handler.updatedvt
    layers:
      - !Ref DependenciesLambdaLayer
    events:
      - httpApi:
          path: /{maDonViTinh}
          method: put
  
  deletedvt:
    handler: handler.deletedvt
    layers:
      - !Ref DependenciesLambdaLayer
    events:
      - httpApi:
          path: /{maDonViTinh}
          method: delete
